version: '3'

networks:
  backend:
  network:

services:
  db:
    image: postgres:16.2-alpine
    container_name: book_store_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BookStoreDB
      - POSTGRES_DB=book_store_db
      - TZ=UTC
    ports:
      - '5432:5432'
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
    networks:
      - backend

  ngrok:
    container_name: ngrok_be
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=2Z7O3YLL6lVZ1Cx5V45BsF2iVdW_4M1fhj9VFRmTvuwCs1XT6
      - NGROK_REGION=sa
    ports:
      - '4040:4040'
    command: http host.docker.internal:8080
    tty: true
  
