version: '3'

networks:
  backend:
  network:

services:
  db:
    image: postgres:16.2-alpine
    container_name: book_store_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BookStoreDB
      - POSTGRES_DB=book_store_db
      - TZ=UTC
    ports:
      - '5432:5432'
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
    networks:
      - backend

  
