import Home from './Home/Home';
import Profile from './Profile/Profile';
import Login from './Authen/Login/Login';
import Register from './Authen/Register/Register';
import About from './About/About';
import Contact from './Contact/Contact';
import Product from './Product/Product';
import User from './User/User';
import Cart from './Cart/Cart';
export { Home, Profile, Login, Register, About, Contact, User, Product, Cart };
export * from './Admin';
