spring:
    application:
        name: book_store_be
    datasource:
        url: jdbc:postgresql://localhost:5432/book_store_db
        username: postgres
        password: BookStoreDB
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 463878333575-e4ehb2h7l1m1ngm569k36roeluu049m6.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile,email
                    facebook:
                        client-id: 1000666255400262
                        client-secret: 4ada11a6a787f361fdab2e9464b0e79a

    mail:
        host: pro55.emailserver.vn
        port: 465
        username: admin@khiemcongdinh.id.vn
        password: Khiem_2004
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        enable: true

s3:
    accessKey: AKIARYEUCDWNVCIE3ZAN
    secretKey: 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
    bucketName: bookbazaar-project
springdoc:
    api-docs:
        path: /api-docs
application:
    security:
        jwt:
            secret-key: 36d40671a0dfd75dc62f1e0b7e72f73a11b418e51cc62adc7d06febce98c01ef
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days
client:
    url: http://localhost:3000

information:
    nameShop: Book Bazaar
    emailShop: admin@khiemcongdinh.id.vn
    ccGmailShop: phamthihue3340@gmail.com
