server:
  tomcat:
      relaxed-query-chars: ['[',']']
spring:
    application:
        name: book_store_be
    datasource:
        url: jdbc:postgresql://localhost:5432/book_store_db
        username: postgres
        password: BookStoreDB
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id:
                        client-secret:
                        scope: profile,email
                    facebook:
                        client-id:
                        client-secret:

    mail:
        host: pro55.emailserver.vn
        port: 465
        username: admin@khiemcongdinh.id.vn
        password: Khiem_2004
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        enable: true

s3:
    accessKey:
    secretKey:
    bucketName: bookbazaar-project
springdoc:
    api-docs:
        path: /api-docs
application:
    security:
        jwt:
            secret-key: 36d40671a0dfd75dc62f1e0b7e72f73a11b418e51cc62adc7d06febce98c01ef
            expiration: 86400000 # a day
client:
    url: http://localhost:3000

information:
    nameShop: Book Bazaar
    emailShop: admin@khiemcongdinh.id.vn
    ccGmailShop: phamthihue3340@gmail.com
ghtk:
    api:
        url: 
        urlProduction: 
        token: 
    pickup:
        province: "
        district:
        ward:
        address:
PAYOS:
  CLIENT_ID:
  API_KEY:
  CHECKSUM_KEY: